[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn qcorn.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
DEBUG = "False"
ALLOWED_HOSTS = "web-production-a522d.up.railway.app"
SECURE_SSL_REDIRECT = "True"
CSRF_COOKIE_SECURE = "True"
SESSION_COOKIE_SECURE = "True"
