[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
PYTHON_VERSION = "3.9.18"
PORT = "8000"

[[services.ports]]
port = 8000

[[services.ports.handlers]]
type = "http"

[[services.ports.handlers.proxy]]
preserve_path = true
