[phases.setup]
nixPkgs = ["nixpkgs.nix"]

[phases.build]
cmd = "pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"

[start]
cmd = "gunicorn qcorn.wsgi:application --bind 0.0.0.0:$PORT"
